version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Update package repositories
          command: sudo apt-get update

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: sudo apt-get install -y awscli

      # Build Angular app
      - run:
          name: Build Angular app
          command: npm run build

      # Deploy to S3 and invalidate CloudFront cache
      - deploy:
          name: Deploy to S3 and invalidate CloudFront cache
          command: |
      aws s3 sync dist/app-crud1 s3://my-angular-content --delete \
        --region $REGION \
        --access-key-id $AWS_ACCESS_KEY_ID \
        --secret-access-key $AWS_SECRET_ACCESS_KEY
      aws configure set preview.cloudfront true
      aws cloudfront create-invalidation --distribution-id E1O65PNRA6OZ23 --paths "/*" \
        --access-key-id $AWS_ACCESS_KEY_ID \
        --secret-access-key $AWS_SECRET_ACCESS_KEY

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
